version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=Luyendkdk1
      - xpack.security.enabled=false
    network_mode: host
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    network_mode: host
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=checkpoint-project-client
      - POSTGRES_PASSWORD=Luyendkdk1
    network_mode: host
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    # ports:
    #   - '6379:6379'
    network_mode: host
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    network_mode: host
    container_name: zoo1
    volumes:
      - ./data/zoo1:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: 172.29.119.193:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    network_mode: host
    container_name: kafka1
    volumes:
      - ./data/kafka1:/var/lib/kafka/data
      - ./certs:/etc/kafka/secrets
    environment:
      KAFKA_ADVERTISED_LISTENERS: SSL://172.29.119.193:9093,PLAINTEXT://172.29.119.193:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,SSL:SSL,PLAINTEXT:PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_ZOOKEEPER_CONNECT: "172.29.119.193:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: 172.29.119.193
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: sslkey_creds
      KAFKA_SSL_KEY_CREDENTIALS: sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
    depends_on:
      - zoo1

volumes:
  cache:
    driver: local
  esdata:
    driver: local
  pgdata:
    driver: local
  kafka1:
    driver: local
  zoo1:
    driver: local