openapi: 3.0.0
info:
  title: VCS-SMS API Specification
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/login:
    post:
      summary: Login a user
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /report:
    post:
      summary: Send a report
      tags:
        - report
      security:
        - TokenAuthorization: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendReportRequest'
      responses:
        '200':
          description: Report sent successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /servers:
    get:
      summary: Get server information
      tags:
        - server
      security:
        - TokenAuthorization: []
      parameters:
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
        - $ref: '#/components/parameters/Name'
        - $ref: '#/components/parameters/Ipv4'
        - $ref: '#/components/parameters/Status'
      responses:
        '200':
          description: Server information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetServersResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new server
      tags:
        - server
      security:
        - TokenAuthorization: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateServerRequest'
      responses:
        '200':
          description: Server created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateServerResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /servers/export:
    get:
      summary: Export servers
      tags:
        - server
      security:
        - TokenAuthorization: []
      parameters:
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
        - $ref: '#/components/parameters/Name'
        - $ref: '#/components/parameters/Ipv4'
        - $ref: '#/components/parameters/Status'
      responses:
        '200':
          description: Servers exported successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportServersResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /servers/import:
    post:
      summary: Import servers
      tags:
        - server
      security:
        - TokenAuthorization: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ImportServersRequest'
      responses:
        '200':
          description: Servers imported successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportServersResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /servers/{id}:
    patch:
      summary: Update a server
      tags:
        - server
      security:
        - TokenAuthorization: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Server ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateServerRequest'
      responses:
        '200':
          description: Server updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateServerRequest'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a server
      tags:
        - server
      security:
        - TokenAuthorization: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Server ID
      responses:
        '200':
          description: Server deleted successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /users/:
    post:
      summary: Create a new user
      tags:
        - user
      security:
        - TokenAuthorization: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '200':
          description: User created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /users/{id}/scopes:
    put:
      summary: Update user scopes
      tags:
        - user
      security:
        - TokenAuthorization: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserScopeRequest'
      responses:
        '200':
          description: User scopes updated successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
components:
  securitySchemes:
    TokenAuthorization:
      type: apiKey
      in: header
      name: Authorization
  parameters:
    PageSize:
      in: query
      name: page_size
      schema:
        type: integer
        default: 10
      required: false
      description: Number of servers per page
    Page:
      in: query
      name: page
      schema:
        type: integer
        default: 1
      required: false
      description: Page number
    Sort:
      in: query
      name: sort
      schema:
        type: string
        default: created_time
      required: false
      description: Sort by field
    Order:
      in: query
      name: order
      schema:
        type: string
        default: desc
        enum: [asc, desc]
      required: false
      description: Order by field
    Name: 
      in: query
      name: name
      schema:
        type: string
        enum: [server_name, status, ipv4, created_time]
      required: false
      description: Server name
    Ipv4:
      in: query
      name: ipv4
      schema:
        type: string
      required: false
      description: Server ipv4
    Status:
      in: query
      name: status
      schema:
        type: string
        enum: ["on", "off"]
      required: false
      description: Server status
  schemas:
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    RegisterResponse:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    SendReportRequest:
      type: object
      properties:
        start_date:
          type: string
        end_date:
          type: string  
        email:
          type: string
    CreateServerRequest:
      type: object
      properties:
        name:
          type: string
        ipv4:
          type: string
        status:
          type: integer
    ExportServersResponse:
      type: object
      properties:
        message:
          type: string
        url:
          type: string
    ImportServersRequest:
      type: object
      properties:
        file:
          format: binary
    ImportServersResponse:
      type: object
      properties:
        message:
          type: string
        data:
          properties:
            success_count:
              type: integer
            failure_count:
              type: integer
            success_names:
              type: array
              items:
                type: string
    UpdateServerRequest:
      type: object
      properties:
        serverData:
          type: string
    CreateUserRequest:
      type: object
      properties:
        username:
          type: string
          example: "luyendd9"
        password:
          type: string
          example: "luyendd"
        scopes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: "api-server:write"
    UpdateUserScopeRequest:
      type: object
      properties:
        message:
          type: string
        data:
          properties:
            username:
              type: string
            password:
              type: string
            scopes:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    example: "api-server:read-write"
    ErrorResponse:  
      type: object
      properties:
        message:
          type: string
    CreateServerResponse:
      type: object
      properties:
        message:
          type: string
        data:
          properties:
            ID:
              type: string
            Name:
              type: string
            Ipv4:
              type: string
            Status:
              type: integer
            CreatedTime:
              type: string
    GetServersResponse:
      type: object
      properties:
        message:
          type: string
        data:
          properties:
            ID:
              type: string
            Name:
              type: string
            Ipv4:
              type: string
            Status:
              type: integer
            CreatedTime:
              type: string
    