openapi: '3.0.2'
info:
  title: VCS-SMS API Specification
  version: '1.0'
servers:
  - url: localhost:8081
paths:
  /servers:
    get:
      summary: Get all servers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
components:
  schemas:
    Server:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time