// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/service.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UptimeCheckRequest struct {
	StartTime            int64    `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UptimeCheckRequest) Reset()         { *m = UptimeCheckRequest{} }
func (m *UptimeCheckRequest) String() string { return proto.CompactTextString(m) }
func (*UptimeCheckRequest) ProtoMessage()    {}
func (*UptimeCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df99c249f22271d5, []int{0}
}

func (m *UptimeCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UptimeCheckRequest.Unmarshal(m, b)
}
func (m *UptimeCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UptimeCheckRequest.Marshal(b, m, deterministic)
}
func (m *UptimeCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UptimeCheckRequest.Merge(m, src)
}
func (m *UptimeCheckRequest) XXX_Size() int {
	return xxx_messageInfo_UptimeCheckRequest.Size(m)
}
func (m *UptimeCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UptimeCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UptimeCheckRequest proto.InternalMessageInfo

func (m *UptimeCheckRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *UptimeCheckRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type UptimeCheckResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UptimeCheckResponse) Reset()         { *m = UptimeCheckResponse{} }
func (m *UptimeCheckResponse) String() string { return proto.CompactTextString(m) }
func (*UptimeCheckResponse) ProtoMessage()    {}
func (*UptimeCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df99c249f22271d5, []int{1}
}

func (m *UptimeCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UptimeCheckResponse.Unmarshal(m, b)
}
func (m *UptimeCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UptimeCheckResponse.Marshal(b, m, deterministic)
}
func (m *UptimeCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UptimeCheckResponse.Merge(m, src)
}
func (m *UptimeCheckResponse) XXX_Size() int {
	return xxx_messageInfo_UptimeCheckResponse.Size(m)
}
func (m *UptimeCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UptimeCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UptimeCheckResponse proto.InternalMessageInfo

func (m *UptimeCheckResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *UptimeCheckResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*UptimeCheckRequest)(nil), "UptimeCheckRequest")
	proto.RegisterType((*UptimeCheckResponse)(nil), "UptimeCheckResponse")
}

func init() {
	proto.RegisterFile("grpc/service.proto", fileDescriptor_df99c249f22271d5)
}

var fileDescriptor_df99c249f22271d5 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2,
	0xe3, 0x12, 0x0a, 0x2d, 0x28, 0xc9, 0xcc, 0x4d, 0x75, 0xce, 0x48, 0x4d, 0xce, 0x0e, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe5, 0xe2, 0x2a, 0x2e, 0x49, 0x2c, 0x2a, 0x89, 0x07, 0xc9,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x71, 0x82, 0x45, 0x42, 0x32, 0x73, 0x53, 0x85, 0x24,
	0xb9, 0x38, 0x52, 0xf3, 0x52, 0x20, 0x92, 0x4c, 0x60, 0x49, 0xf6, 0xd4, 0xbc, 0x14, 0x90, 0x94,
	0x92, 0x3b, 0x97, 0x30, 0x8a, 0x79, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x52, 0x5c, 0x1c,
	0x45, 0x50, 0x36, 0xd8, 0x38, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x84, 0x8b, 0x35, 0xb5, 0xa8, 0x28,
	0xbf, 0x08, 0x6c, 0x14, 0x67, 0x10, 0x84, 0x63, 0x84, 0xea, 0xb0, 0x60, 0x88, 0xa3, 0x85, 0x2c,
	0xb8, 0xb8, 0x91, 0x44, 0x85, 0x84, 0xf5, 0x30, 0x1d, 0x2f, 0x25, 0xa2, 0x87, 0xc5, 0x05, 0x4e,
	0x1c, 0x51, 0x6c, 0x7a, 0xfa, 0xa0, 0x00, 0x48, 0x62, 0x03, 0xfb, 0xdc, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x8a, 0x90, 0x10, 0xb9, 0x0f, 0x01, 0x00, 0x00,
}
