version: '3.7'
services:
  healthcheck-server:
    image: luyend785/healthcheck-server:0.0.2
    network_mode: host
    environment:
      - GRPC_HOST=172.29.119.193
      - GRPC_PORT=50069
      - DB_HOST=172.29.119.193
      - DB_PASS=Luyendkdk1
      - REDIS_HOST=172.29.119.193:6379
      - REDIS_PWD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - ELASTIC_ENDPOINT=http://172.29.119.193:9200
      - KAFKA_BOOTSTRAP_SERVERS=ssl://172.29.119.193:9093
      - KAFKA_SSL_CA_LOCATION=/usr/local/bin/certs/ca-cert.pem
      - KAFKA_SSL_CERTIFICATE_LOCATION=/usr/local/bin/certs/client-cert.pem
      - KAFKA_SSL_KEY_LOCATION=/usr/local/bin/certs/client-key.pem
      - KAFKA_SSL_KEY_PASSWORD=password
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/local/bin/gcpkey/secure-gizmo-420615-9aed8aa861d1.json
    volumes:
      - /mnt/c/Users/luyen/Desktop/vcs-sms/certs:/usr/local/bin/certs
      - /mnt/c/Users/luyen/Desktop/vcs-sms/gcpkey:/usr/local/bin/gcpkey